[package]
name = "rent"
version = "0.1.0"
edition = "2021"
description = "A Ent implementation for Rust"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
